name: Simple Invite
version: 0.1
author: Chloroplast
authors: [Chloroplast, Busti3000]
main: b2c.simpleinvite.SimpleInvite
commands:
  invite:
    description: Invite a user to play on this server. When this user does something bad you will get a strike.
    usage: /&lt;command&gt <username> <reason>
  simpleinvite:
    description: List all simpleinvite commands.
    usage: |
      /&lt;command&gt -List all simpleinvite commands
      /&lt;command&gt reason <username> -Display the reason this user was invited.
      /&lt;command&gt strikes <username> -Display the amount of strikes this user has.
      /&lt;command&gt reload -Reload the configuration file.
      /&lt;command&gt list -shows a list of all Invites from the player
      /&lt;command&gt list <username> -shows a list of all Invites from the player


permissions:
  simpleinvite.invite:
    description: Allows a user to invite others.
  simpleinvite.reason:
    description: Allows a user to use the /reason command
  simpleinvite.strikes:
    description: Allows a user to use the /strikes command
    simpleinvite.list:
        description: Allows a user to use the /list <user> command (not /list)